### ISSUE TITLE
No registration for invited team mates

### ISSUE THREAD

**Issue by jebinshaju** [aryan877/glitch#1]
The profiles of team mates are automatically created when the accept the invitaion via mail.

**Comment by aryan877** [comment]
Hey @jebinshaju, this is indeed how the Appwrite SDK is supposed to work. It bypasses registration as the email is verified as it's accepted through the email itself. I'm closing this issue for now since that is indeed how the feature was supposed to be.

<img width="1012" alt="Screenshot 2023-07-11 at 5 19 01 PM" src="https://github.com/aryan877/glitch/assets/38075578/a9adc1ac-c664-4ce6-8f88-d0955c39e692">
